adds CascadeCreateUpdate
openziti/foundation pull request #294
Opened 2022-01-17 18:30 UTC by andrewpmartinez

I don't think I'm missing something adding the type seems to enforce on create/update and does nothing on delete.

2022-01-17 19:03 UTC, ekoby approved these changes

2022-01-17 21:19 UTC, plorenz commented
It works, but it would better to not add the fkDeleteConstraint at all if given that type. That way we don't scan on delete.

2022-01-17 21:20 UTC, plorenz requested changes
Avoid adding fkDeleteConstraint if using new constraint type

2022-01-18 00:16 UTC, andrewpmartinez commented on storage/boltz/indexes.go
> +	if cascade != CascadeCreateUpdate {
Let me know if this covers your comment @plorenz

2022-01-18 14:20 UTC, plorenz approved these changes

2022-01-18 14:27 UTC, merged